### PR TITLE
Fixes #22. Don't include oEmbed endpoint in embed URL

### LINKED ISSUE #22: oEmbed implementation
Opening here from DallasMorningNews/django-chartwerk#23.

### PR DESCRIPTION
**Pull request by achavez**
I attempted to fix the oEmbed URL to track with changes in DallasMorningNews/django-chartwerk#23.

I would rather have this surface the URL to the chart in the editor (`{{ chartwerk_url }}/chart/{{ chart_slug }}`), but that may not be practical given what we have in the state.

### CODE REVIEW

**Comment by achavez** [comment]
Also, @hobbes7878 I just realized I don't know how to actually get this into `django-chartwerk` if I did end up doing this the right way.

**Comment by hobbes7878** [comment]
Right. So I have a post install script that runs after you npm install this lib and asks if you want to "unpack" the bundled assets. One of the options is to unpack to django's static directory from our usual staticapp setup. I need to re-trace the whole oEmbed thing tomorrow to approve this one, but I can re-deploy the lib in django-chartwerk then.

**Comment by hobbes7878** [comment]
I think we can now make the `oembed` context object a boolean [here](https://github.com/DallasMorningNews/django-chartwerk/blob/master/chartwerk/views.py#L70) & [here](https://github.com/DallasMorningNews/chartwerk-editor/blob/master/src/templates/django-chartwerk-editor.html#L22).

**Comment by achavez** [comment]
@hobbes7878 I like that idea

**Comment by achavez** [comment]
Closing this in favor of #24

**Pull request closed without merging**
